const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),nf=new Intl.NumberFormat('vi-VN',{maximumFractionDigits:0}),fmt=n=>nf.format(n||0),pct=n=>((n||0)*100).toLocaleString('vi-VN',{maximumFractionDigits:1})+'%',compact=n=>Math.abs(n)>=1e9?(n/1e9).toLocaleString('vi-VN',{maximumFractionDigits:2})+' tỷ':(n/1e6).toLocaleString('vi-VN',{maximumFractionDigits:1})+' tr';
const sheetNames=['Giải DT TTTC','CN.KV DT','TLTT RB','TOP 1 GĐ mỗi vùng 1','Giải CBB mỗi Vùng','Giải CBB TTTC','Giải BDM','Giải Vùng.Miền'];let data,index=0,page=1,filtered=[];const labels=['Doanh thu TTTC','Doanh thu CN/KV','Tái tục RB','Top 1 GĐ mỗi vùng','CBB mỗi vùng','CBB TTTC','BDM','Vùng & Miền'];
function normRegion(v){return String(v||'').replace(/Vùng\s*0?(\d+)(B)?/i,(_,n,b)=>'Vùng '+n.padStart(2,'0')+(b||''))}
function normalize(s,i){return s.records.map((r,pos)=>{let region=normRegion(r['Vùng']||(r.name?.startsWith('Vùng')?r.name:''));let domain=r['Miền']||(r.name?.startsWith('Miền')?r.name:'');if(!domain&&region){const num=+(region.match(/\d+/)||[0])[0];domain=num<=6?'Miền Bắc':'Miền Nam'}return {raw:r,pos,name:r['Họ và Tên']||r['BDM phụ trách']||r['CN/PGD/TTTC']||r['Chi nhánh/ Khu vực']||r['Trung tâm']||r.name,code:r['MÃ DAO']||r['Mã CN']||r['Mã Book']||'',branch:r['Tên CN']||'',region,domain,revenue:r['Doanh thu']??r.revenue??0,contracts:r['Số HĐBH']??0,rate:r['Tỷ lệ tái tục']??r['TLTT']??0,awardRate:r['TLTT xét thưởng']??r['Tỷ lệ tái tục']??0,gap:r['Doanh thu còn thiếu']??r.gap70??0,eligible:r['SL xe có khả năng tái tục']??0,renewed:r['SL xe tái tục']??r['Xe TT']??0,prize:r['Ước thưởng']||r['Ước giải thưởng']||r['Giải thưởng']||'',gap70:r.gap70,gap100:r.gap100,group:r['Nhóm đối tượng'],prizeCount:r['Số giải đạt được']}})}
function options(id,values){$(id).innerHTML='<option value="">Tất cả</option>'+[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'vi',{numeric:true})).map(v=>`<option>${esc(v)}</option>`).join('')}
function selectTab(i){if(!data)return;index=i;page=1;$('search').value='';$('sort').value='metric';let rows=normalize(data.sheets[i],i);options('domain',rows.map(r=>r.domain));options('region',rows.map(r=>r.region));$('tabs').innerHTML=data.sheets.map((s,j)=>`<button data-tab="${j}" class="${j===i?'active':''}" aria-pressed="${j===i}">${labels[j]}</button>`).join('');$('tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>selectTab(+b.dataset.tab));render()}
function metric(r){return index===6?r.awardRate:index===2?r.rate:r.revenue}
function global(){let ratio=data.actual/data.plan;$('global').innerHTML=`<div><span>Doanh thu toàn chương trình</span><strong>${compact(data.actual)}</strong><small>${fmt(data.actual)} VND</small></div><div><span>Kế hoạch chương trình</span><strong>${compact(data.plan)}</strong><small>${fmt(data.plan)} VND</small></div><div><span>Hoàn thành kế hoạch</span><strong>${pct(ratio)}</strong><div class="track"><i style="width:${Math.min(100,ratio*100)}%"></i></div><small>Còn ${compact(Math.max(0,data.plan-data.actual))} đến kế hoạch</small></div>`;$('source').textContent='Nguồn: '+data.source;$('tabs').setAttribute('aria-label','8 hạng mục giải')}
function bars(rows,percent=false){let max=Math.max(...rows.map(r=>r.value),1e-10);return rows.length?rows.map(r=>`<div class="barrow"><span class="name" title="${esc(r.name)}">${esc(r.name)}</span><div class="bar"><i style="width:${Math.max(0,r.value/max*100)}%"></i></div><b>${percent?pct(r.value):compact(r.value)}</b></div>`).join(''):'<div class="empty">Không có dữ liệu phù hợp.</div>'}
function stat(label,value,note=''){return `<div class="stat"><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`}
function render(){if(!data)return;const query=$('search').value.toLocaleLowerCase('vi');filtered=normalize(data.sheets[index],index).filter(r=>(!$('domain').value||r.domain===$('domain').value)&&(!$('region').value||r.region===$('region').value)&&(!query||[r.name,r.code,r.branch,r.region].join(' ').toLocaleLowerCase('vi').includes(query)));filtered.sort((a,b)=>$('sort').value==='source'?a.pos-b.pos:$('sort').value==='gap'?Math.max(0,a.gap)-Math.max(0,b.gap)||b.revenue-a.revenue:metric(b)-metric(a)||b.revenue-a.revenue);let sum=filtered.reduce((a,r)=>a+r.revenue,0),el=filtered.reduce((a,r)=>a+r.eligible,0),rn=filtered.reduce((a,r)=>a+r.renewed,0);$('sheetname').textContent=data.sheets[index].name;$('title').textContent=labels[index];$('count').textContent=filtered.length+' đối tượng hiển thị';let isRate=index===2||index===6;let mention=filtered.filter(r=>r.prize).length;
if(index===7){let only=filtered.filter(r=>r.region),regions=only.length,regionsSum=only.reduce((a,r)=>a+r.revenue,0);$('stats').innerHTML=stat('Doanh thu vùng',compact(regionsSum),'Chỉ cộng các dòng vùng')+stat('Số vùng',fmt(regions))+stat('Chạm mốc 70 triệu',fmt(filtered.filter(r=>r.gap70<=0).length),'Theo cột doanh thu còn thiếu')+stat('Chạm mốc 100 triệu',fmt(filtered.filter(r=>r.gap100<=0).length),'Vùng và miền xét riêng')}
else $('stats').innerHTML=stat(isRate?'Tỷ lệ tái tục gộp':'Doanh thu đang lọc',isRate?(el?pct(rn/el):'—'):compact(sum),isRate?'Số xe tái tục / số xe có khả năng':'Trong hạng mục đang xem')+stat(index===0||index===1?'Số HĐBH':'Số đối tượng',fmt(index===0||index===1?filtered.reduce((a,r)=>a+r.contracts,0):filtered.length))+stat(isRate?'Số xe tái tục':'Chạm mốc doanh thu',fmt(isRate?rn:filtered.filter(r=>r.gap<=0).length),isRate?'Theo dữ liệu gốc':'Chưa xác nhận đạt giải')+stat('Có ước thưởng trong file',fmt(mention),'Không đồng nghĩa đã đủ điều kiện');
$('charttitle').textContent='Top 10 · '+(index===6?'TLTT xét thưởng':index===2?'Tỷ lệ tái tục':'Doanh thu');$('unit').textContent=isRate?'Đơn vị: %':'Đơn vị: tỷ / triệu VND';let top=[...filtered].sort((a,b)=>metric(b)-metric(a)).slice(0,10);$('chart').innerHTML=bars(top.map(r=>({name:r.name,value:metric(r)})),isRate);
let groups={};filtered.forEach(r=>{if(index===7&&!r.region)return;let k=r.region||r.domain||'Chưa phân vùng';groups[k]??={revenue:0,eligible:0,renewed:0};groups[k].revenue+=r.revenue;groups[k].eligible+=r.eligible;groups[k].renewed+=r.renewed});let breakdown=Object.entries(groups).map(([name,g])=>({name,value:isRate?(g.eligible?g.renewed/g.eligible:0):g.revenue})).sort((a,b)=>b.value-a.value);$('sideTitle').textContent=isRate?'Tái tục gộp theo vùng':'Doanh thu theo vùng';$('sideUnit').textContent=isRate?'Theo số xe':'Không cộng dòng miền';$('breakdown').innerHTML=bars(breakdown,isRate);
$('hint').textContent=index===7?'Dòng miền và dòng vùng thể hiện các cấp tổng hợp khác nhau. Mốc người thân giữ nguyên số liệu gốc khi xem chi tiết.':index===3?'Xếp hạng tham khảo theo doanh thu. Chọn một vùng để so sánh ứng viên; ước thưởng giữ nguyên file nguồn.':index===6?'Xếp theo TLTT xét thưởng; tỷ lệ gộp tính theo số xe. Không dùng TLTT gộp thay TLTT xét thưởng.':'Tiến độ mốc doanh thu = doanh thu / (doanh thu + doanh thu còn thiếu). Ước thưởng giữ nguyên file nguồn.';
let cols=index===7?['Đối tượng','Doanh thu','Thiếu mốc 70tr','Thiếu mốc 100tr','Chênh lệch mốc người thân (gốc)']:index===6?['BDM phụ trách','Vùng','Miền','Xe có khả năng TT','Xe tái tục','TLTT','TLTT xét thưởng','TLTT còn thiếu (gốc)','Ước thưởng']:['Đơn vị / Cá nhân','Mã','Vùng','Miền',...(index===4||index===5?['Chi nhánh']:[]),'Doanh thu',...(index===0||index===1?['Số HĐBH']:[]),...(index===2||index===3?['TLTT','Xe có khả năng TT','Xe tái tục']:[]),'DT còn thiếu','Tiến độ mốc DT',...(index===0?['Nhóm','Số giải (file)']:[]),'Ước thưởng'];$('thead').innerHTML='<tr><th>#</th>'+cols.map(c=>`<th>${c}</th>`).join('')+'</tr>';
const pages=Math.max(1,Math.ceil(filtered.length/20));page=Math.min(page,pages);$('tbody').innerHTML=filtered.slice((page-1)*20,page*20).map((r,j)=>{let cells=[];const cell=(v,cls='')=>`<td class="${cls}">${v}</td>`,money=n=>cell(fmt(n),'num');cells.push(cell(esc(r.name),'namecell'));if(index===7){cells.push(money(r.revenue),money(r.gap70),money(r.gap100),r.raw.extra==null?cell('—'):money(r.raw.extra))}else if(index===6){cells.push(cell(esc(r.region)),cell(esc(r.domain)),money(r.eligible),money(r.renewed),cell(pct(r.rate),'num'),cell(pct(r.awardRate),'num'),cell(pct(r.raw['TLTT còn thiếu']),'num'),cell(r.prize?`<span class="badge">${esc(r.prize)}</span>`:'—'))}else{cells.push(cell(esc(r.code)),cell(esc(r.region)),cell(esc(r.domain)));if(index===4||index===5)cells.push(cell(esc(r.branch)));cells.push(money(r.revenue));if(index===0||index===1)cells.push(money(r.contracts));if(index===2||index===3)cells.push(cell(pct(r.rate),'num'),money(r.eligible),money(r.renewed));cells.push(money(r.gap));let target=r.revenue+r.gap,p=target>0?r.revenue/target:0;cells.push(cell(`<div class="track"><i style="width:${Math.max(0,Math.min(100,p*100))}%"></i></div><small>${target>0?pct(p):'—'}</small>`,'progresscell'));if(index===0)cells.push(cell(esc(r.group)),money(r.prizeCount));cells.push(cell(r.prize?`<span class="badge">${esc(r.prize)}</span>`:'—'))}return `<tr><td><span class="rank ${(page-1)*20+j<3?'top':''}">${(page-1)*20+j+1}</span></td>${cells.join('')}</tr>`}).join('')||`<tr><td colspan="20" class="empty">Không tìm thấy kết quả. Thử xóa bộ lọc.</td></tr>`;$('page').textContent=`${page} / ${pages}`;$('prev').disabled=page===1;$('next').disabled=page===pages;$('tablecount').textContent=filtered.length+' dòng · 20 dòng/trang'}
['domain','region','search','sort'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',()=>{page=1;render()}));$('reset').onclick=()=>selectTab(index);$('prev').onclick=()=>{page--;render()};$('next').onclick=()=>{page++;render()};function message(t){$('message').textContent=t;$('message').style.display='block';setTimeout(()=>$('message').style.display='none',6500)}
$('upload').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{if(f.size>20*1024*1024)throw Error('File vượt quá 20 MB.');const wb=XLSX.read(await f.arrayBuffer(),{type:'array'});let sheets=sheetNames.map(name=>({name})).map(s=>{if(!wb.SheetNames.includes(s.name))throw Error('Thiếu sheet: '+s.name);const rows=XLSX.utils.sheet_to_json(wb.Sheets[s.name],{header:1,defval:null});if(s.name==='Giải Vùng.Miền'){const records=rows.filter(r=>typeof r[0]==='string'&&/^(Miền|Vùng)/.test(r[0])&&typeof r[1]==='number').map(r=>({name:r[0],revenue:r[1],gap70:r[2],gap100:r[3],extra:r[4]}));if(!records.length)throw Error('Sheet Vùng.Miền không có dữ liệu.');return {name:s.name,records}}let h=rows.findIndex(r=>r[0]==='STT'&&(r.some(x=>String(x).trim()==='Doanh thu')||r.includes('TLTT')));if(h<0)throw Error('Không nhận diện tiêu đề: '+s.name);let heads=rows[h].map(x=>x?String(x).trim():'');const records=rows.slice(h+1).filter(r=>typeof r[0]==='number').map(r=>Object.fromEntries(heads.map((k,i)=>[k,typeof r[i]==='string'?r[i].trim():r[i]]).filter(([k])=>k)));if(!records.length)throw Error('Không có dữ liệu: '+s.name);if(records.some(r=>typeof(r['Doanh thu']??r['TLTT'])!=='number'))throw Error('Cần lưu Excel với kết quả công thức đã tính: '+s.name);return {name:s.name,headers:heads,records}});let rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1});const value=label=>{let r=rows.find(r=>String(r[0]).trim()===label);return r?.find(v=>typeof v==='number')};let plan=value('Doanh thu kế hoạch:'),actual=value('Doanh thu thực hiện:');if(!(plan>0)||typeof actual!=='number')throw Error('Thiếu kế hoạch hoặc doanh thu toàn chương trình.');data={sheets,plan,actual,source:f.name+' · cập nhật trên thiết bị'};document.querySelectorAll('.filters input,.filters select,.filters button').forEach(e=>e.disabled=false);global();selectTab(index);message('Đã nạp dữ liệu mới. Dữ liệu chỉ dùng trong phiên hiện tại; mở lại trang sẽ về file mẫu.')}catch(err){message('Chưa thể nạp file: '+err.message)}finally{e.target.value=''}};
$('source').textContent='Chọn file Excel CTTĐ trên thiết bị để bắt đầu.';
$('title').textContent='Nạp Excel để xem dữ liệu';
$('chart').innerHTML='<div class="empty">Biểu đồ xuất hiện sau khi nạp Excel.</div>';
$('breakdown').innerHTML='<div class="empty">Dữ liệu được xử lý trên thiết bị của bạn.</div>';
$('tbody').innerHTML='<tr><td class="empty">Chưa có dữ liệu. Bấm “Nạp Excel mới” ở phía trên.</td></tr>';
$('prev').disabled=true;$('next').disabled=true;
document.querySelectorAll('.filters input,.filters select,.filters button').forEach(e=>e.disabled=true);
if(document.modelContext?.registerTool)document.modelContext.registerTool({name:'filter_contest_dashboard',description:'Chọn hạng mục giải và lọc theo vùng hoặc từ khóa trên dashboard.',inputSchema:{type:'object',properties:{award:{type:'integer',minimum:0,maximum:7},region:{type:'string'},search:{type:'string'}},required:['award'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!data)throw Error('Dữ liệu chưa sẵn sàng');if(!Number.isInteger(input.award)||input.award<0||input.award>7||input.region!=null&&typeof input.region!=='string'||input.search!=null&&typeof input.search!=='string')throw Error('Bộ lọc không hợp lệ');if(input.region&&!normalize(data.sheets[input.award],input.award).some(r=>r.region===input.region))throw Error('Không có vùng này');selectTab(input.award);$('region').value=input.region||'';$('search').value=input.search||'';render();return {award:labels[index],rows:filtered.length}}});
